backend:
  name: github
  repo: SummittDweller/compass-rose-band
  branch: main
media_folder: 'static/images'
public_folder: /images
collections:
  - name: 'performance'
    label: 'Performance'
    folder: 'content/performance'
    create: true
    slug: '{{slug}}'
    path: '{{year}}/{{slug}}'
    preview_path: '{{year}}/{{slug}}'
    editor:
      preview: true
    fields:
      - label: Title
        name: title
      - label: Type
        name: type
        default: performance
      - label: Date
        name: date
        hint: Enter the date of the performance.
      - label: Start Time
        name: startTime
      - label: End Time
        name: endTime
      - label: City
        name: city
      - label: Body
        name: body
        widget: markdown
      - label: Publish Date
        name: publishDate
        widget: date
      - label: Last Mod
        name: lastmod
        widget: datetime
      - label: Location
        name: location
        required: false
      - label: Draft Status
        name: draft
        widget: boolean
        default: false
      - label: Description
        name: description
        required: false
      - label: Venues
        name: venues
        widget: list
        default: [" "]
        comment: "Enter comma separated values."
        required: false
